version: '3.8'

services:
  nginx:
    container_name: fullcycle-nginx
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: ./app
    container_name: fullcycle-app
    entrypoint: dockerize -wait tcp://fullcycle-db:3306 -timeout 20s
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: fullcycle-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:

